# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  DJANGO_ALLOWED_HOSTS: {{ join "," .Values.service.hosts | quote }}
  {{- if .Values.database.usePostgres }}
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "django-polls"
  DB_HOST: "django-app-postgresdb"
  DB_PORT: {{ .Values.database.postgresSettings.port | quote }}
  {{- else}}
  DB_ENGINE: "django.db.backends.sqlite3"
  DB_NAME: "/app/db/db.sqlite3"
  {{- end}}
